repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        stages: [commit]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
default_language_version:
  python: python3.7
exclude:
  'venv/*'
default_stages: [commit-msg]
