repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        stages: [commit]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        stages: [commit]
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        stages: [commit]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests]
        files: .py$
        stages: [push]
default_language_version:
  python: python3.7
exclude:
  'venv/*'
default_stages: [commit-msg]
